In [ ]:
# !pip install auto-sklearn
# !pip install xgboost


In [ ]:
!pip install auto-sklearn==0.10.0
!pip install -U scikit-learn
!python -m pip show scikit-learn
!python -c "import sklearn; sklearn.show_versions()"

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
# import autosklearn
from sklearn.metrics import accuracy_score, f1_score
import os


In [2]:
path = "/content/drive/MyDrive/Ecoenergy/Results/"

dred = "new_dred_01_20230516.xlsx"
qud = "new_qud_01_20230516.xlsx"
 

# importer le dataset
rw_dred =  pd.read_excel( path + dred)
rw_qud  =  pd.read_excel( path + qud)


rw_dred.head()

In [4]:
rw_qud.iloc[ : , 1:-5 ]

oc1  oc2  oc3          p1          p2          p3       pn1       pn2  \
0        1    1    1    0.000000    0.000000  166.429993 -0.002259 -0.002259   
1        1    1    1    0.000000  166.429993  159.550003 -0.002259  0.007632   
2        1    1    1  166.429993  159.550003  143.270004  0.007632  0.007223   
3        1    1    1  159.550003  143.270004  175.880005  0.007223  0.006255   
4        1    1    1  143.270004  175.880005  176.660004  0.006255  0.008193   
...    ...  ...  ...         ...         ...         ...       ...       ...   
46922    1    1    1   -2.840000   -1.710000   -1.870000 -0.002428 -0.002361   
46923    1    1    1   -1.710000   -1.870000   -1.640000 -0.002361 -0.002370   
46924    1    1    1   -1.870000   -1.640000  -10.640000 -0.002370 -0.002357   
46925    1    1    1   -1.640000  -10.640000   79.220001 -0.002357 -0.002892   
46926    1    1    1  -10.640000   79.220001   74.379997 -0.002892  0.002449   

            pn3        pt01  ...  cl2  cl3       ptn01       ptn02    ptn03   \
0      0.007632    0.000000  ...    1    3   -0.000023 -166.430023 -0.000023   
1      0.007223 -166.429993  ...    3    3 -166.430023   -0.000023 -0.000023   
2      0.006255    0.000000  ...    3    3   -0.000023   -0.000023 -0.000023   
3      0.008193    0.000000  ...    3    3   -0.000023   -0.000023 -0.000023   
4      0.008240    0.000000  ...    3    3   -0.000023   -0.000023 -0.000023   
...         ...         ...  ...  ...  ...         ...         ...       ...   
46922 -0.002370    0.000000  ...    0    0   -0.000023   -0.000023 -0.000023   
46923 -0.002357    0.000000  ...    0    0   -0.000023   -0.000023 -0.000023   
46924 -0.002892    0.000000  ...    0    0   -0.000023   -0.000023 -0.000023   
46925  0.002449    0.000000  ...    0    0   -0.000023   -0.000023 -0.000023   
46926  0.002161    0.000000  ...    0    0   -0.000023   -0.000023 -0.000023   

            ptn11       ptn22       ptn33  out  temps_lecture  
0      166.430023  166.430023  166.430023    3              2  
1        0.000023    0.000023    0.000023    3              2  
2        0.000023    0.000023    0.000023    3              2  
3        0.000023    0.000023    0.000023    3              2  
4        0.000023    0.000023    0.000023    3              2  
...           ...         ...         ...  ...            ...  
46922    0.000023    0.000023    0.000023    0              2  
46923    0.000023    0.000023    0.000023    0              2  
46924    0.000023    0.000023    0.000023    0              2  
46925    0.000023    0.000023    0.000023    0              2  
46926    0.000023    0.000023    0.000023    0              2  

[46927 rows x 26 columns]

In [5]:
rw_dred.iloc[ : , 1:-3 ]

oc1  oc2  oc3   p1   p2   p3      pn1      pn2      pn3  pt01  ...  \
0         1    1    0  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
1         1    0    1  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
2         0    1    0  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
3         1    0    1  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
4         0    1    0  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
...     ...  ...  ...  ...  ...  ...      ...      ...      ...   ...  ...   
166345    1    1    0  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
166346    1    0    1  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
166347    0    1    0  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
166348    1    0    0  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   
166349    0    0    1  0.0  0.0  0.0 -0.68907 -0.68907 -0.68907   0.0  ...   

        cl2  cl3     ptn01     ptn02     ptn03     ptn11     ptn22     ptn33  \
0         0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
1         0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
2         0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
3         0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
4         0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
...     ...  ...       ...       ...       ...       ...       ...       ...   
166345    0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
166346    0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
166347    0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
166348    0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   
166349    0    0  0.000001  0.000001  0.000001 -0.000001 -0.000001 -0.000001   

        out  temps_lecture  
0         0              5  
1         0              5  
2         0              5  
3         0              5  
4         0              5  
...     ...            ...  
166345    0              5  
166346    0              5  
166347    0              5  
166348    0              5  
166349    0              5  

[166350 rows x 26 columns]

In [6]:
qud_feature = rw_qud.iloc[ : , 1:-5 ].drop( 'out' , axis = 1 )
qud_target  = rw_qud.iloc[ : , 1:-5 ].out

qud_features_train = qud_feature.iloc[ : int(qud_feature.shape[0]*0.8 ) , : ]
qud_features_test  = qud_feature.iloc[ int(qud_feature.shape[0]*0.8 ) : , : ]  

qud_target_train = qud_target.iloc[ : int(qud_feature.shape[0]*0.8 ) ]
qud_target_test  = qud_target.iloc[ int(qud_feature.shape[0]*0.8 ) : ]  

In [7]:
dred_feature = rw_dred.iloc[ : , 1:-3 ].drop( 'out' , axis = 1 )
dred_target  = rw_dred.iloc[ : , 1:-3 ].out

dred_features_train = dred_feature.iloc[ : int(dred_feature.shape[0]*0.8 ) , : ]
dred_features_test  = dred_feature.iloc[ int(dred_feature.shape[0]*0.8 ) : , : ]  

dred_target_train = dred_target.iloc[ : int(dred_feature.shape[0]*0.8 ) ]
dred_target_test  = dred_target.iloc[ int(dred_feature.shape[0]*0.8 ) : ]  

Machine Learning (ML)

In [22]:
# qud

xgb = XGBClassifier()


xgb.fit(qud_features_train, qud_target_train)
yhat = xgb.predict(qud_features_test)

print(f"Les scores de chaque classe: \n{f1_score(qud_target_test, yhat, average = None)}")

print()
macro = f1_score(qud_target_test, yhat, average = "macro")
print(f"Les scores de ENSEMBLE classe: \n{macro}")


Les scores de chaque classe: 
[0.95920423 0.99038462 0.99056604 0.85700758 0.98122821]

Les scores de ENSEMBLE classe: 
0.9556781341734244


In [23]:
# dred

xgb = XGBClassifier()


xgb.fit(dred_features_train, dred_target_train)
yhat = xgb.predict(dred_features_test)


print(f"Les scores de chaque classe: \n{f1_score(dred_target_test, yhat, average = None)}")

print()
macro = f1_score(dred_target_test, yhat, average = "macro")
print(f"Les scores de ENSEMBLE classe: \n{macro}")



Les scores de chaque classe: 
[0.56005981 0.9939302  0.02932551 0.47487376 0.50098116]

Les scores de ENSEMBLE classe: 
0.5118340865185163


In [3]:
# les donnees provenant de simulated dataset

all_files_list = os.listdir(path)

recherche = "new_subsim" # fichiers de `simulated`
files_sim = [element.replace(".xlsx", "") for element in all_files_list if recherche in element]


all_data = {fichier : pd.read_excel( path + f"{fichier}.xlsx") for fichier in files_sim }


for fichier, data in all_data.items() :
  # print(fichier)
  tmp = data.iloc[: , 1:-5]
  input = tmp.drop(["out"] , axis=1)
  output = data["out"]
  if data["out"].nunique() == 5:
    print(f"{fichier}==================== Classes OK")
    ## separation en train et test
    datas_train = input.iloc[ : int(input.shape[0]*0.8 ) , : ]
    datas_test  = input.iloc[ int(input.shape[0]*0.8 ) : , : ]  

    output_train = output.iloc[ : int(input.shape[0]*0.8 ) ]
    output_test  = output.iloc[ int(input.shape[0]*0.8 ) : ]  

    xgb = XGBClassifier()


    xgb.fit(datas_train, output_train)
    yhat = xgb.predict(datas_test)

    print(f"Les scores de chaque classe: \n{f1_score(output_test, yhat, average = None)}")

    print()
    macro = f1_score(output_test, yhat, average = "macro")
    print(f"Les scores de ENSEMBLE classe: \n{macro}\n\n")
    
  else:
    print(f"{fichier}==================== Absence de certaines classes\n\n")


new_subsim1_01_20230516==================== Absence de certaines classes


new_subsim2_01_20230516==================== Classes OK
Les scores de chaque classe: 
[0.75179778 0.         0.07731959 0.00970874 0.43098958]

Les scores de ENSEMBLE classe: 
0.25396313722396097


new_subsim3_01_20230516==================== Classes OK
Les scores de chaque classe: 
[0.84379968 0.59202454 0.58536585 0.07434944 0.15642458]

Les scores de ENSEMBLE classe: 
0.4503928197911164


new_subsim4_01_20230516==================== Classes OK
Les scores de chaque classe: 
[0.64362001 1.         1.         0.03713528 0.46160446]

Les scores de ENSEMBLE classe: 
0.6284719502722643


new_subsim5_01_20230516==================== Classes OK
Les scores de chaque classe: 
[0.48684628 0.99435028 1.         0.02583026 0.45706558]

Les scores de ENSEMBLE classe: 
0.5928184802791726


new_subsim0_01_20230516==================== Absence de certaines classes




In [ ]:
# print autosklearn version
# import autosklearn
# print('autosklearn: %s' % autosklearn.__version__)


Deep Machine Learning (DML)